### ISSUE TITLE
REVIEW: filesize-test.py

### ISSUE THREAD

**Issue by laissezfarrell** [dd388/everybody-scripts#18]
Maggie and Shira worked on this in September and want feedback from the group. Hoping we can do this asynchronously.

**Comment by bonniegee** [comment]
This looks great! I made some changes to the syntax, they're at a [branch of my fork](https://github.com/bonniegee/everybody-scripts/blob/filesizeFunction/filesize-test.py) 
If you look at commits for the branch, you can see the changes I made

**Comment by laissezfarrell** [comment]
Group tested @bonniegee's branch 2019-01-30. Made one change to make it work. Created, reviewed, and merged pull request.
