### ISSUE TITLE
Verify getDirectory function

### ISSUE THREAD

**Issue by dd388** [dd388/everybody-scripts#6]

**Comment by laissezfarrell** [comment]
Make validator function either run over a set of files (if source directory is a directory of flat files) or recurse through subdirectories (if source directory contains other directories).

**Comment by laissezfarrell** [comment]
So this works as a standalone script on my local machine. Incorporated into validator.py and interested in how it works as part of the larger set of processes.

**Comment by laissezfarrell** [comment]
note to f: look at comments in validator.py on the else statements in this section (lines 31-38)

**Comment by dd388** [comment]
Integrated into the work of https://github.com/dd388/everybody-scripts/issues/11
